# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EuclDist2D <- function(x, y) {
    .Call(`_GLoSS_EuclDist2D`, x, y)
}

krig <- function(beta, R0, R1, Rmix0, Rmix1, Rnew0, Rnew1, delta, mu) {
    .Call(`_GLoSS_krig`, beta, R0, R1, Rmix0, Rmix1, Rnew0, Rnew1, delta, mu)
}

krig_gamma <- function(beta, R0, Rmix0, Rnew0, mu) {
    .Call(`_GLoSS_krig_gamma`, beta, R0, Rmix0, Rnew0, mu)
}

gloss <- function(y, X, hyper, R = 2000L, B = 1000L, Trace = 0L) {
    .Call(`_GLoSS_gloss`, y, X, hyper, R, B, Trace)
}

closs <- function(y, X, hyper, R = 2000L, B = 1000L, Trace = 0L) {
    .Call(`_GLoSS_closs`, y, X, hyper, R, B, Trace)
}

vloss <- function(y, X, hyper, R = 2000L, B = 1000L, Trace = 0L) {
    .Call(`_GLoSS_vloss`, y, X, hyper, R, B, Trace)
}

spgp <- function(y, X, hyper, R = 2000L, B = 1000L, Trace = 0L) {
    .Call(`_GLoSS_spgp`, y, X, hyper, R, B, Trace)
}

